# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - tasks/**
      - .github/workflows/tasks-main.yml
  pull_request:
    branches: [ main ]
    paths:
      - tasks/**
      - .github/workflows/tasks-main.yml

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tasks
    steps:
    # Clonar repositorio
    - uses: actions/checkout@v3
    # Usar node version 14
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    # Cargar cache de node_modules
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v1
      with:
        path: node_modules
        # se carga el cache siempre y cuando sea el mismo sistema operativo y el package-lock no cambio
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    # Instalar dependencias
    - name: Install dependencies
      # Si se cargo cache no ejecutar
      if: steps.node-cache.outputs.cache-hit != 'true' 
      run: npm install
    # Generar compilación de producción
    - name: Run Build command
      run: npm run build --prod
    # Ejecutar pruebas unitarias
    - name: Run Unit tests
      run: npm run test --configuration=ci
